-- Table PAIEMENT
CREATE TABLE IF NOT EXISTS PAIEMENT (
    ID_PAIEMENT    INT AUTO_INCREMENT PRIMARY KEY,
    TYPE_PAIEMENT  VARCHAR(20)    NOT NULL DEFAULT 'Passager' COMMENT 'Passager ou Colis',
    ID_PASSAGER    INT            NULL,
    ID_COLIS       INT            NULL,
    ID_VOYAGE      INT            NULL,
    MONTANT        DECIMAL(12,2)  NOT NULL DEFAULT 0,
    MODE_PAIEMENT  VARCHAR(50)    NOT NULL DEFAULT 'Espèces' COMMENT 'Espèces, Mobile Money, Virement, Chèque',
    STATUT         VARCHAR(30)    NOT NULL DEFAULT 'Payé' COMMENT 'Payé, En attente, Annulé',
    DATE_PAIEMENT  DATETIME       NOT NULL DEFAULT NOW(),
    NOTES          TEXT           NULL,
    FOREIGN KEY (ID_PASSAGER) REFERENCES PASSAGER(ID_PASSAGER) ON DELETE SET NULL,
    FOREIGN KEY (ID_COLIS)    REFERENCES COLIS(ID_COLIS)       ON DELETE SET NULL,
    FOREIGN KEY (ID_VOYAGE)   REFERENCES VOYAGE(ID_VOYAGE)     ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
