CREATE TABLE IF NOT EXISTS PLAN_COMPTABLE (
    ID_PLAN_COMPTABLE INT NOT NULL AUTO_INCREMENT,
    NUMERO_COMPTE VARCHAR(50) NOT NULL,
    INTITULE_COMPTE VARCHAR(150) NOT NULL,
    ID_COMPTE_PARENT INT NULL,
    DATE_CREATION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_PLAN_COMPTABLE),
    UNIQUE KEY UK_PLAN_COMPTABLE_NUMERO (NUMERO_COMPTE),
    CONSTRAINT FK_PLAN_COMPTABLE_PARENT
        FOREIGN KEY (ID_COMPTE_PARENT)
        REFERENCES PLAN_COMPTABLE (ID_PLAN_COMPTABLE)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);
